name: CI

on:
  push:
    branches: ["main"]

jobs:
  hello:
    name: deploy to staging
    runs-on: ubuntu-latest

    steps:
      - name: Hello step
        run: echo "Hello from Github actions"

  bye:
    name: deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Bye step
        run: echo "Bye bye"
